Fix/issues fixer
dasch-swiss/sipi pull request #331
Opened 2020-09-23 10:56 UTC by lrosenth

Latest version... Should fix knora.json problem

2020-09-23 11:12 UTC, benjamingeer approved these changes
I can't review this properly without a user story and explanation for each change, and it would be easier to review if each user story was implemented in a separate, smaller pull request. But let's try it. :)

2020-09-23 12:25 UTC, benjamingeer requested changes
Sorry, I forgot something: does this PR fix the version number and commit ID printed on startup?

2020-09-28 09:43 UTC, benjamingeer commented on shttps/Parsing.cpp
> +                {"csv",     {"text/comma-separated-values", "text/plain", "application/vnd.ms-excel",
Currently the `/knora.json` route returns `text/comma-separated-values`  for a CSV file, but this MIME type is unregistered. The registered MIME type for CSV is `text/csv`: https://www.rfc-editor.org/rfc/rfc4180.html

2020-09-28 15:48 UTC, lrosenth commented
@benjamingeer  The csv-mimetype is returned as "text/csv" in the JSON variable "internalMimeType"...
Should now be ready for merge and deployement...

2020-09-29 08:06 UTC, benjamingeer commented
Does this PR fix the version number and commit ID printed on startup (https://dasch.myjetbrains.com/youtrack/issue/DSP-687)?

It would be great to have this automatically updated. CMake can generate a source file with the current Git commit hash: https://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake/4318642#4318642

2020-09-29 08:58 UTC, subotic commented
@benjamingeer I don't think so

> Does this PR fix the version number and commit ID printed on startup (https://dasch.myjetbrains.com/youtrack/issue/DSP-687)?

I don't think so. There is another PR open to solve this. The checksum printed at startup comes already from git and cmake. The only thing missing is the tag. It is next on my list.

2020-09-29 09:08 UTC, benjamingeer approved these changes
> There is another PR open to solve this. The checksum printed at startup comes already from git and cmake. The only thing missing is the tag. It is next on my list.

OK then let's merge this now and make a new Sipi release from it.

2020-09-29 09:22 UTC, merged